apiVersion: apps/v1
kind: Deployment
metadata:
  name: zero-trust-app
  labels:
    app: zero-trust-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zero-trust-app
  template:
    metadata:
      labels:
        app: zero-trust-app
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: zero-trust-app
        # REPLACE with your actual Docker Hub username
        image: blsnabrhm/zero-trust-app:latest 
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: zero-trust-service
spec:
  selector:
    app: zero-trust-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort