apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: k8sblockroot
spec:
  crd:
    spec:
      names:
        kind: K8sBlockRoot
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8sblockroot
        
        violation[{"msg": msg}] {
          # Target Pods
          input.review.object.kind == "Pod"
          
          # Violation occurs if runAsNonRoot is NOT true
          not input.review.object.spec.securityContext.runAsNonRoot
          
          msg := "Zero Trust Violation: Pods must not run as root. Set securityContext.runAsNonRoot to true."
        }