name: Zero Trust DevSecOps Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout Code
        uses: actions/checkout@v4

      - name: 2. Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: maven

      - name: 3. Compile Code
        run: mvn clean package -DskipTests

      # SCA: Software Composition Analysis
      - name: 4. OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        env:
          JAVA_HOME: /opt/jdk
        with:
          project: 'zero-trust-app'
          path: '.'
          format: 'HTML'
        continue-on-error: true 

      - name: 5. Upload OWASP Report
        uses: actions/upload-artifact@v4
        with:
          name: OWASP-Report
          path: ${{github.workspace}}/reports

      - name: 6. Build Docker Image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/zero-trust-app:latest .

      # Container Security Scan
      - name: 7. Trivy Vulnerability Scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ secrets.DOCKERHUB_USERNAME }}/zero-trust-app:latest'
          format: 'table'
          # Set to 0 to observe the vulnerabilities without failing. 
          # In strict Zero Trust, you would change this to 1 to break the build.
          exit-code: '0' 
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: 8. Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 9. Push to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/zero-trust-app:latest